"""add_booking_type_recurring_schedules_overrides

Revision ID: c3670951b806
Revises: b6d5389d3d21
Create Date: 2026-02-20 11:14:16.177732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3670951b806'
down_revision: Union[str, None] = 'b6d5389d3d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'day_of_week', 'start_time', 'end_time', name='uq_recurring_schedule')
    )
    op.create_index(op.f('ix_recurring_schedules_id'), 'recurring_schedules', ['id'], unique=False)
    op.create_table('schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('override_type', sa.Enum('skip', 'replace', name='overridetype'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'date', name='uq_schedule_override')
    )
    op.create_index(op.f('ix_schedule_overrides_id'), 'schedule_overrides', ['id'], unique=False)
    op.add_column('orders', sa.Column('booking_type', sa.Enum('spotlight', 'long_term', name='bookingtype'), nullable=False, server_default='spotlight'))
    op.create_index('ix_space_time_slot_lookup', 'space_time_slots', ['space_id', 'date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_space_time_slot_lookup', table_name='space_time_slots')
    op.drop_column('orders', 'booking_type')
    op.drop_index(op.f('ix_schedule_overrides_id'), table_name='schedule_overrides')
    op.drop_table('schedule_overrides')
    op.drop_index(op.f('ix_recurring_schedules_id'), table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    # ### end Alembic commands ###
